-- Seed script for tbl_employees
INSERT INTO tbl_employees (uuid, username, password, first_name, last_name, full_name, email, position, department, date_hired, status_id, created_at) VALUES
(UUID(), 'john.doe', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'John', 'Doe', 'John Doe', 'john.doe@example.com', 'Developer', 'IT', '2026-01-01', 1, NOW()),
(UUID(), 'jane.smith', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Jane', 'Smith', 'Jane Smith', 'jane.smith@example.com', 'Designer', 'Design', '2026-01-02', 1, NOW()),
(UUID(), 'robert.brown', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Robert', 'Brown', 'Robert Brown', 'robert.brown@example.com', 'Manager', 'Sales', '2026-01-03', 1, NOW()),
(UUID(), 'emily.davis', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Emily', 'Davis', 'Emily Davis', 'emily.davis@example.com', 'Analyst', 'Finance', '2026-01-04', 1, NOW()),
(UUID(), 'michael.wilson', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Michael', 'Wilson', 'Michael Wilson', 'michael.wilson@example.com', 'Support', 'IT', '2026-01-05', 1, NOW()),
(UUID(), 'sarah.miller', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Sarah', 'Miller', 'Sarah Miller', 'sarah.miller@example.com', 'Manager', 'Marketing', '2026-01-06', 1, NOW()),
(UUID(), 'david.taylor', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'David', 'Taylor', 'David Taylor', 'david.taylor@example.com', 'Sales Rep', 'Sales', '2026-01-07', 1, NOW()),
(UUID(), 'jessica.anderson', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Jessica', 'Anderson', 'Jessica Anderson', 'jessica.anderson@example.com', 'HR', 'HR', '2026-01-08', 1, NOW()),
(UUID(), 'james.thomas', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'James', 'Thomas', 'James Thomas', 'james.thomas@example.com', 'Lead', 'IT', '2026-01-09', 1, NOW()),
(UUID(), 'linda.jackson', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Linda', 'Jackson', 'Linda Jackson', 'linda.jackson@example.com', 'Coordinator', 'Marketing', '2026-01-10', 1, NOW()),
(UUID(), 'william.white', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'William', 'White', 'William White', 'william.white@example.com', 'Accountant', 'Finance', '2026-01-11', 1, NOW()),
(UUID(), 'barbara.harris', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Barbara', 'Harris', 'Barbara Harris', 'barbara.harris@example.com', 'Designer', 'Design', '2026-01-12', 1, NOW()),
(UUID(), 'richard.martin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Richard', 'Martin', 'Richard Martin', 'richard.martin@example.com', 'Sales Rep', 'Sales', '2026-01-13', 1, NOW()),
(UUID(), 'susan.thompson', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Susan', 'Thompson', 'Susan Thompson', 'susan.thompson@example.com', 'HR', 'HR', '2026-01-14', 1, NOW()),
(UUID(), 'joseph.garcia', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Joseph', 'Garcia', 'Joseph Garcia', 'joseph.garcia@example.com', 'Developer', 'IT', '2026-01-15', 1, NOW()),
(UUID(), 'margaret.martinez', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Margaret', 'Martinez', 'Margaret Martinez', 'margaret.martinez@example.com', 'Manager', 'Design', '2026-01-16', 1, NOW()),
(UUID(), 'charles.robinson', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Charles', 'Robinson', 'Charles Robinson', 'charles.robinson@example.com', 'Analyst', 'Finance', '2026-01-17', 1, NOW()),
(UUID(), 'karen.clark', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Karen', 'Clark', 'Karen Clark', 'karen.clark@example.com', 'Support', 'IT', '2026-01-18', 1, NOW()),
(UUID(), 'christopher.rodriguez', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Christopher', 'Rodriguez', 'Christopher Rodriguez', 'christopher.rodriguez@example.com', 'Sales Rep', 'Sales', '2026-01-19', 1, NOW()),
(UUID(), 'nancy.lewis', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Nancy', 'Lewis', 'Nancy Lewis', 'nancy.lewis@example.com', 'Marketing', 'Marketing', '2026-01-20', 1, NOW()),
(UUID(), 'daniel.lee', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Daniel', 'Lee', 'Daniel Lee', 'daniel.lee@example.com', 'Developer', 'IT', '2026-01-21', 1, NOW()),
(UUID(), 'betty.walker', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Betty', 'Walker', 'Betty Walker', 'betty.walker@example.com', 'Designer', 'Design', '2026-01-22', 1, NOW()),
(UUID(), 'paul.hall', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Paul', 'Hall', 'Paul Hall', 'paul.hall@example.com', 'Manager', 'Sales', '2026-01-23', 1, NOW()),
(UUID(), 'helen.allen', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Helen', 'Allen', 'Helen Allen', 'helen.allen@example.com', 'Analyst', 'Finance', '2026-01-24', 1, NOW()),
(UUID(), 'mark.young', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Mark', 'Young', 'Mark Young', 'mark.young@example.com', 'Support', 'IT', '2026-01-25', 1, NOW());
